### ISSUE TITLE
edit_item の is_active をボタンに修正

### ISSUE THREAD

**Issue by arinko-ya** [arinko-ya/order-counter#15]
- [x] Edit item の is_active をボタンに修正する
- [x] ボタンの位置は update ボタンの右側とする
- [x] ボタン押下で active/inactive 切り替え
- [x] ボタンの色と Value をそれぞれのステータスに応じて変える
- [x] active -> 緑　inactive -> 赤

**Comment by kaoru-furuta** [comment]
マージされたのでクローズします。
