### ISSUE TITLE
テストランナーの作成

### ISSUE THREAD

**Issue by arinko-ya** [arinko-ya/order-counter#7]
毎回一つ一つ流すのは少し面倒なのでまとめて全テストを流せるようにする。

**Comment by kaoru-furuta** [comment]
@arinko-ya 

テストランナーを作り込むところまで対応する必要があるか検討した方が良さそう。
例えばルートディレクトリで以下のコマンドを実行すると、一発で全テスト実行できます。

`python -m unittest discover app/tests -p '*.py' -v`

ちなみに、unittest が想定するテストファイル名は `test*.py` なので、テストファイル名を `test_order.py` などに変更すると、 `-p` オプションも省けます。

**Comment by arinko-ya** [comment]
ありがとうございます。
記載いただいたコマンドで十分だと思います。
